openapi: 3.1.0
info:
  title: 謎解きLINEアプリ API
  version: '1.0'
  description: 謎解きLINEアプリ用API
paths:
  /user-token:
    get:
      summary: ユーザトークン取得
      operationId: get-user-token
      description: ユーザーのトークンデータを取得します。
      security:
        - LINE ID Token: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                description: ユーザー属性
                properties:
                  userToken:
                    type: string
                    description: ユーザトークン
                    example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsaW5lVXNlcklkIjoiVWE2NDc2MjQzN2NmY2Q5YmNlYTdjZjQzNWM0MDRmZWE5IiwiaWF0IjoxNzE0MDk2NjQ0LCJleHAiOjE3MTQxMDAyNDR9.L90TytPTIYkb-GdCsMcVKuEtxQ3iTmmOMvdXmbULCbb'
                  lineUserId:
                    type: string
                    description: LINEユーザーID
                    pattern: 'U[0-9a-f]{32}'
                    example: U8189cf6745fc0d808977bdb0b9f22995
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

  /profile:
    get:
      summary: プロフィール取得
      operationId: get-profile
      description: ユーザーのプロフィールデータを取得します。
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
              examples:
                プロフィールデータ:
                  value:
                    lineUserId: U4af4980629U4af4980629
                    gender: 2
                    ageGroup: 2
                    residence: '26'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
      parameters: []
    parameters: []
    put:
      summary: プロフィール登録
      operationId: put-profile
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
              examples:
                登録完了:
                  value:
                    lineUserId: U4af4980629U4af4980629
                    gender: 0
                    ageGroup: 1
                    residence: '28'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
      description: ユーザーのプロフィールデータを登録します。
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserProfile'
            examples:
              登録:
                value:
                  gender: 0
                  ageGroup: 1
                  residence: '28'

  /progress:
    get:
      summary: ゲーム進捗取得
      tags: []
      operationId: get-progress
      description: ゲームの進捗データを取得します。
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Progress'
              examples:
                解けた謎がある場合:
                  value:
                    isOnboardingCompleted: true
                    completedMissionList:
                      - mission1
                      - mission2
                解けた謎がない場合:
                  value:
                    isOnboardingCompleted: true
                    completedMissionList: []
                オンボーディングが完了していない場合:
                  value:
                    isOnboardingCompleted: false
                    completedMissionList: []
                通常謎を全て解いた場合:
                  value:
                    isOnboardingCompleted: true
                    completedMissionList:
                      - mission1
                      - mission2
                      - mission3
                      - mission4
                全謎（大謎含む）を解いた場合:
                  value:
                    isOnboardingCompleted: true
                    completedMissionList:
                      - mission1
                      - mission2
                      - mission3
                      - mission4
                      - grandMission
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
    parameters: []

  /answer/{id}:
    post:
      summary: 謎の答え送信
      operationId: post-answer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: 答えの正誤判定結果
                  progress:
                    $ref: '#/components/schemas/Progress'
              examples:
                通常謎正解の場合:
                  value:
                    result: true
                    progress:
                      isOnboardingCompleted: true
                      completedMissionList:
                        - mission1
                        - mission2
                大謎正解の場合:
                  value:
                    result: true
                    progress:
                      isOnboardingCompleted: true
                      completedMissionList:
                        - mission1
                        - mission2
                        - mission3
                        - mission4
                        - grandMission
                答えが誤りの場合:
                  value:
                    result: false
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
      description: 謎の答えを送信します。
      parameters:
        - schema:
            $ref: '#/components/schemas/MissionId'
          in: path
          name: 'id'
          description: 対象の謎ID（mission1-4:通常謎、grandMission:大謎）
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                answer:
                  type: string
                  description: 謎の答え
              required:
                - answer
    parameters: []

  /awards:
    get:
      summary: プレゼントの受け取り状況取得
      operationId: get-awards
      description: プレゼントの受け取り状況を取得します。
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                description: ''
                properties:
                  awardList:
                    type: array
                    description: 受け取り済みプレゼントIDの一覧
                    minItems: 0
                    maxItems: 2
                    items:
                      $ref: '#/components/schemas/AwardId'
              examples:
                プレゼント未受取:
                  value:
                    awardList: []
                クリア賞受け取り済み:
                  value:
                    awardList:
                      - complete
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
    post:
      summary: プレゼントの受け取り状態記録
      operationId: post-awards
      description: プレゼントの受け取り状態を記録します。
      parameters:
        - schema:
            $ref: '#/components/schemas/AwardId'
          in: query
          name: id
          description: プレゼントID
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  awardList:
                    type: array
                    description: 受け取り済みプレゼントIDの一覧
                    minItems: 0
                    maxItems: 1
                    items:
                      $ref: '#/components/schemas/AwardId'
              examples:
                受け取り完了:
                  value:
                    awardList:
                      - complete
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
    parameters: []

  /surveys:
    get:
      summary: アンケート回答状況取得
      operationId: get-surveys
      description: アンケートの回答状況を取得します。
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  surveyList:
                    type: array
                    description: 回答済みアンケートIDの一覧
                    minItems: 0
                    maxItems: 2
                    items:
                      $ref: '#/components/schemas/SurveyId'
              examples:
                初期状態:
                  value:
                    surveyList: []
                アンケート回答済み:
                  value:
                    surveyList:
                      - complete
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
    post:
      summary: アンケート回答状態記録
      operationId: post-surveys
      description: アンケートの回答状態を記録します。
      parameters:
        - schema:
            $ref: '#/components/schemas/SurveyId'
          in: query
          name: id
          description: アンケートID
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  surveyList:
                    type: array
                    description: 回答済みアンケートIDの一覧
                    minItems: 0
                    maxItems: 2
                    items:
                      $ref: '#/components/schemas/SurveyId'
              examples:
                アンケート回答完了:
                  value:
                    surveyList:
                      - complete
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
    parameters: []

  /complete-onboarding:
    post:
      summary: オンボーディング完了
      operationId: post-complete-onboarding
      description: オンボーディングが完了した状態を記録します。
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Progress'
              examples:
                オンボーディング完了:
                  value:
                    isOnboardingCompleted: true
                    completedMissionList: []
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

components:
  schemas:
    # Enum定義
    MissionId:
      type: string
      description: 謎ID
      enum:
        - mission1
        - mission2
        - mission3
        - mission4
        - grandMission
      example: mission1

    AwardId:
      type: string
      description: プレゼントID
      enum:
        - ex
        - complete
      example: ex

    SurveyId:
      type: string
      description: アンケートID
      enum:
        - ex
        - complete
      example: complete
    UserProfile:
      title: UserProfile
      type: object
      description: ユーザープロフィール
      properties:
        lineUserId:
          type: string
          description: LINEユーザーID
          pattern: 'U[0-9a-f]{32}'
          example: U8189cf6745fc0d808977bdb0b9f22995
        gender:
          type: integer
          description: 性別（0:女性, 1:男性, 2:無回答）
          enum:
            - 0
            - 1
            - 2
        ageGroup:
          type: integer
          description: 年代（0:10代以下, 1:20代, 2:30代, 3:40代, 4:50代, 5:60代, 6:70代以上）
          enum:
            - 0
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
          example: 2
        residence:
          type: string
          description: 居住地（都道府県コード）
          example: '26'
          pattern: '^(0[1-9]|[1-3][0-9]|4[0-7])$'
      required:
        - gender
        - ageGroup
        - residence

    Error:
      title: Error
      type: object
      description: エラー
      properties:
        message:
          type: string
          description: エラーメッセージ
        errorParams:
          type: array
          description: 不正があるリクエスト項目の一覧
          items:
            type: string

    Progress:
      title: Progress
      type: object
      description: ゲームの進捗
      properties:
        isOnboardingCompleted:
          type: boolean
          description: オンボーディングの完了状態
          example: true
        completedMissionList:
          type: array
          description: 解いた謎IDの一覧（mission1-4:通常謎、grandMission:大謎）
          minItems: 0
          maxItems: 5
          items:
            $ref: '#/components/schemas/MissionId'
      required:
        - isOnboardingCompleted
        - completedMissionList

    # エラーレスポンス
    UnauthorizedError:
      type: object
      description: 401 Unauthorizedエラー
      properties:
        message:
          type: string
          example: 'Unauthorized'
      required:
        - message

    BadRequestError:
      type: object
      description: 400 Bad Requestエラー
      properties:
        message:
          type: string
          example: 'Bad Request'
        errorParams:
          type: array
          description: 不正があるリクエスト項目の一覧
          items:
            type: string
      required:
        - message

    NotFoundError:
      type: object
      description: 404 Not Foundエラー
      properties: {}

    InternalServerError:
      type: object
      description: 500 Internal Server Errorエラー
      properties:
        message:
          type: string
          example: 'Internal Server Error'
      required:
        - message

  securitySchemes:
    LINE ID Token:
      name: line-id-token
      type: apiKey
      in: header
      description: LINE ID Token for user authentication
    Bearer Token:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: User token for API authentication

security:
  - Bearer Token: []
servers:
  - url: 'http://127.0.0.1:4010'
    description: localhost
